version: '3'
services:
  api:
    container_name: hasaki-api
    build: .
    ports:
      - "8022:80"
    volumes:
      - .:/var/www/hasaki-api
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "hasaki"
    ports:
      - "3377:3306"
